server:
  port: 8084
  servlet:
    context-path: /poker
  forward-headers-strategy: framework

spring:
  application:
    name: poker-tracker
  datasource:
    url: jdbc:mysql://192.168.2.102:3306/poker?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  thymeleaf:
    cache: false
    mode: HTML


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: poker_
